// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5HB7PPfrIXhG3o4aa0RkrTBwsU4PGv0',
    appId: '1:168720893974:web:a5a7f9ad5714e8e0a40d37',
    messagingSenderId: '168720893974',
    projectId: 'tokiomarine-app',
    authDomain: 'tokiomarine-app.firebaseapp.com',
    storageBucket: 'tokiomarine-app.firebasestorage.app',
    measurementId: 'G-JV9NZHVBZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64SeFw9xX3BPPu4u9nFyrnvVdd2j_GII',
    appId: '1:168720893974:android:29161685701ac5bba40d37',
    messagingSenderId: '168720893974',
    projectId: 'tokiomarine-app',
    storageBucket: 'tokiomarine-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCATowzHBOiOQ4h6GI1AdNpQtVeBgS5JBE',
    appId: '1:168720893974:ios:0d05799dcfe79441a40d37',
    messagingSenderId: '168720893974',
    projectId: 'tokiomarine-app',
    storageBucket: 'tokiomarine-app.firebasestorage.app',
    iosBundleId: 'com.hugoferreira.tokiomarine',
  );
}
